services:
  database:
    image: mariadb:11.3-rc
    environment:
      MARIADB_USER: ${E_DB_USER}
      MARIADB_ROOT_PASSWORD: ${E_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${E_DB_DATABASE}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/00-create-tables.sql
      - ./db_data:/var/lib/mysql
    ports:
      - 3333:3306
    restart: always

  processor:
    build:
      context: .
      dockerfile: gpxprocessor/docker/processor.dockerfile
    environment:
      DB_HOST: ${E_DB_HOST}
      DB_PORT: ${E_DB_PORT}
      DB_USER: ${E_DB_USER}
      DB_ROOT_PASSWORD: ${E_DB_ROOT_PASSWORD}
      DB_DATABASE: ${E_DB_DATABASE}
    depends_on:
      - database
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/docker/backend.dockerfile
    environment:
      DB_HOST: ${E_DB_HOST}
      DB_PORT: ${E_DB_PORT}
      DB_USER: ${E_DB_USER}
      DB_ROOT_PASSWORD: ${E_DB_ROOT_PASSWORD}
      DB_DATABASE: ${E_DB_DATABASE}
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/docker/frontend.dockerfile
    depends_on:
      - backend
    ports:
      - 4200:80
    restart: always
