services:
  database:
    image: mariadb:11.3-rc
    environment:
      MARIADB_USER: ${E_DB_USER}
      MARIADB_ROOT_PASSWORD: ${E_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${E_DB_DATABASE}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3333:3306
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    depends_on:
      - backend
    ports:
      - 4200:80
    restart: always
